export interface PrefillFormData {
  external_id: string;
  name: string;
  address_line_1: string;
  address_city: string;
  address_state: string;
  address_postal_code: string;
  tin: string;
  owner1_first_name: string;
  owner1_last_name: string;
  owner1_email: string;
  owner1_mobile: string;
  owner1_ssn: string;
  owner1_dob: string;
  owner1_address_line_1: string;
  owner1_address_city: string;
  owner1_address_state: string;
  owner1_address_postal: string;
  owner1_address_country: string;
  owner1_title: string;
  owner1_owner_type: string;
  owner1_ownership_percentage: number;
  applicant_first_name: string;
  applicant_last_name: string;
  applicant_email: string;
  applicant_subrole_code: string;
  generate_invite_link: boolean;
  is_simple_flow: boolean;
}
